[2025-10-06T18:35:20.581+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-10-06T18:35:20.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Airflow_Lab1.calculate_cluster_stats manual__2025-10-06T18:34:54.008566+00:00 [queued]>
[2025-10-06T18:35:20.593+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Airflow_Lab1.calculate_cluster_stats manual__2025-10-06T18:34:54.008566+00:00 [queued]>
[2025-10-06T18:35:20.593+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-10-06T18:35:20.598+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): calculate_cluster_stats> on 2025-10-06 18:34:54.008566+00:00
[2025-10-06T18:35:20.603+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=649) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-10-06T18:35:20.604+0000] {standard_task_runner.py:63} INFO - Started process 661 to run task
[2025-10-06T18:35:20.604+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Airflow_Lab1', 'calculate_cluster_stats', 'manual__2025-10-06T18:34:54.008566+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/***.py', '--cfg-path', '/tmp/tmppabc435j']
[2025-10-06T18:35:20.606+0000] {standard_task_runner.py:91} INFO - Job 21: Subtask calculate_cluster_stats
[2025-10-06T18:35:20.624+0000] {task_command.py:426} INFO - Running <TaskInstance: Airflow_Lab1.calculate_cluster_stats manual__2025-10-06T18:34:54.008566+00:00 [running]> on host a8f2a950ef1c
[2025-10-06T18:35:20.663+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='your_name' AIRFLOW_CTX_DAG_ID='Airflow_Lab1' AIRFLOW_CTX_TASK_ID='calculate_cluster_stats' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T18:34:54.008566+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T18:34:54.008566+00:00'
[2025-10-06T18:35:20.663+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-10-06T18:35:20.877+0000] {logging_mixin.py:188} INFO - Cluster Counts: {0: 5541, 2: 2280, 1: 815}
[2025-10-06T18:35:20.877+0000] {logging_mixin.py:188} INFO - Cluster Centers:
[[0.04379098 0.0125208  0.07549284]
 [0.35395379 0.04597106 0.3498421 ]
 [0.08585621 0.03234155 0.25701904]]
[2025-10-06T18:35:20.877+0000] {logging_mixin.py:188} INFO - Inertia (SSE): 91.64796947554566
[2025-10-06T18:35:20.878+0000] {python.py:237} INFO - Done. Returned value was: {'cluster_counts': {0: 5541, 2: 2280, 1: 815}, 'cluster_centers': [[0.04379098254655095, 0.012520800863003586, 0.07549283844152602], [0.3539537876227555, 0.045971057135783144, 0.3498421013676325], [0.08585620803229539, 0.03234155155075013, 0.2570190420809446]], 'inertia': 91.64796947554566}
[2025-10-06T18:35:20.878+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-10-06T18:35:20.882+0000] {xcom.py:675} ERROR - keys must be str, int, float, bool or None, not numpy.int32. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2025-10-06T18:35:20.882+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 486, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3197, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 246, in set
    value = cls.serialize_value(
            ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/xcom.py", line 673, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
TypeError: keys must be str, int, float, bool or None, not numpy.int32
[2025-10-06T18:35:20.887+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Airflow_Lab1, task_id=calculate_cluster_stats, run_id=manual__2025-10-06T18:34:54.008566+00:00, execution_date=20251006T183454, start_date=20251006T183520, end_date=20251006T183520
[2025-10-06T18:35:20.893+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 21 for task calculate_cluster_stats (keys must be str, int, float, bool or None, not numpy.int32; 661)
[2025-10-06T18:35:20.908+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-10-06T18:35:20.920+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-06T18:35:20.921+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
